POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2OWQ4ZmMwYjc1ZjY0OTM5ZTI5NjcyZmYiLCJpYXQiOjE3NzU4Mjg2MzAsImV4cCI6MTc3NTgzMjIzMH0.SbgYO966L90RxawFXrHMIbRSWuhj20u-ZrrMX9UgLoM
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 7
}

