POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1jb2RleCIsImlkIjoiNjliNDA1MzkzNDcwM2UxOWY2NzczMzU4IiwiaWF0IjoxNzczNDA2ODk5LCJleHAiOjE3NzM0MTA0OTl9.jadQOXWySORuooVSEZ2mGF7E6aIfcDyYe_pymNGQVYo
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 7
}

